### ISSUE TITLE
Cannot search files on Finder

### ISSUE THREAD

**Issue by ozguncagri** [bazil/bazil#20] opened 2020-03-12 06:53 UTC
I'm using "bazil.org/fuse", "bazil.org/fuse/fs" packages to create my own file system but mounted file systems are not searchable through Finder. Finder tries to find items but is says nothing but Loading and spinning loader icon. Do I miss something or it's some kind of bug?

Here is my **fuse.MountOptions**

- fuse.FSName("samplevolume")
- fuse.Subtype("sample")
- fuse.VolumeName("Sample Volume")
- fuse.AsyncRead()
- fuse.ReadOnly()

and I'm optionally adding fuse.LocalVolume() option depending on flag but nothing changed.

Thanks for packages BTW :)

**Comment by tv42** [comment] 2020-03-12 20:26
That sounds most likely a bug in your filesystem. There is not enough information here to say anything else. Try something known to work, like https://github.com/bazil/zipfs or https://github.com/bazil/bolt-mount

**Comment by ozguncagri** [comment] 2020-03-12 21:19
I tried to implement it using examples (hello and clockfs) but I'll try zipfs and bolt-mount implementations asap and I'll send more info about it. Thanks

**Comment by ozguncagri** [comment] 2020-03-13 05:18
Update: I just tried to run zipfs. It connects zip file (zipfs source codes zip) to mount point successfully but it has same problem. Here is screenshot;

<img width="887" alt="Screen Shot 2020-03-13 at 08 15 01" src="https://user-images.githubusercontent.com/946294/76591981-f0a66c80-6502-11ea-83c5-cae9e137a4ff.png">

That loading is never ends. My fuse version is 3.10.4 and my OS is macOS Catalina 10.15.3 (19D76). It can be bug in the code because zipfs has same problem.

**Comment by tv42** [comment] 2020-03-19 16:20
So what filesystem activity happens during that Finder spin? Enable the debug log.

**Comment by ozguncagri** [comment] 2020-03-20 10:36
Here is my log outputs file of my sample file system. I simply mounted it opened mounted drive and see the files and typed something to the search field then unmounted drive.

Log File : [out.log](https://github.com/bazil/bazil/files/4359008/out.log)

**Comment by tv42** [comment] 2020-03-20 20:18
That log has no timestamps and the exact same number of request and responses -> it cannot be used to say anything about any delays potentially caused by the FUSE server. Mostly it looks like Finder tries to open a bunch of files that don't exist in your filesystem (looks to be just xattr kludge files).

**Comment by ozguncagri** [comment] 2020-03-20 22:06
So is there anything I can do or it's all about FUSE server on macOS? If you need I can give you log with timestamps but previous one is sequential output from fuse package.

**Comment by tv42** [comment] 2020-09-14 19:05
Unfortunately there's no viable open source FUSE for macOS anymore. Closing this, there's not much I can do. For more information, see https://github.com/bazil/fuse/issues/224

**Closed as completed by tv42** 2020-09-14 19:05 UTC
Labels: platform:osx, need-more-info
